In [1]:
import cv2  # type: ignore
import os
import time
import numpy as np  # type: ignore

import mediapipe as mp  # type: ignore

from matplotlib import pyplot as plt # type: ignore
from mediapipe.tasks import python  # type: ignore
from mediapipe.tasks.python import vision  # type: ignore
from mediapipe.framework.formats import landmark_pb2 # type: ignore

In [2]:
drawer = mp.solutions.drawing_utils # drawing utilities
VisionRunningMode = mp.tasks.vision.RunningMode

In [3]:
face_base_options = python.BaseOptions(model_asset_path="./tasks/face_landmarker.task")
hand_base_options = python.BaseOptions(model_asset_path="./tasks/hand_landmarker.task")
pose_base_options = python.BaseOptions(model_asset_path="./tasks/pose_landmarker.task")

In [4]:
face_options = vision.FaceLandmarkerOptions(
    base_options=face_base_options,
    output_face_blendshapes=True,
    output_facial_transformation_matrixes=True,
    num_faces=1,
    running_mode=VisionRunningMode.VIDEO,
)

hand_options = vision.HandLandmarkerOptions(
    base_options=hand_base_options,
    num_hands=2,
    running_mode=VisionRunningMode.VIDEO,
)

pose_options = vision.PoseLandmarkerOptions(
    base_options=pose_base_options,
    output_segmentation_masks=True,
    running_mode=VisionRunningMode.VIDEO,
)


face_detector = vision.FaceLandmarker.create_from_options(face_options)
hand_detector = vision.HandLandmarker.create_from_options(hand_options)
pose_detector = vision.PoseLandmarker.create_from_options(pose_options)

In [5]:
LandmarkList = landmark_pb2.NormalizedLandmarkList
NormalizedLandmark = landmark_pb2.NormalizedLandmark


def create_landmark_list(landmarks, num_keypoints):
    """Creates a LandmarkList protocol buffer from a list of landmarks or fills with empty values if no landmarks are provided.

    Args:
        landmarks: A list of landmark objects, each containing x, y, z coordinates.
        num_keypoints: The number of keypoints to be included in the LandmarkList.

    Returns:
        A LandmarkList containing the converted landmarks or empty values if no landmarks are provided.
    """
    # generate empty landmarks with all coordinates set to 0.0
    empty_landmarks = [
        NormalizedLandmark(x=0.0, y=0.0, z=0.0) for _ in range(num_keypoints)
    ]

    return LandmarkList(
        landmark=(
            # convert provided landmarks to NormalizedLandmark objects or use empty landmarks
            [NormalizedLandmark(x=lm.x, y=lm.y, z=lm.z) for lm in landmarks]
            if landmarks
            else empty_landmarks
        )
    )


def extract_keypoints_for_drawing(face_results, pose_results, hand_results):
    """Converts face, pose, and hand landmarks to corresponding protocol buffer lists for drawing.

    Args:
        face_results: Object containing face landmark detection results.
        pose_results: Object containing pose landmark detection results.
        hand_results: Object containing hand landmark detection results.

    Returns:
        A tuple containing three LandmarkList messages: face_landmarks, pose_landmarks, and hand_landmarks.
    """
    # convert face landmarks to LandmarkList, using empty values if no landmarks are present
    face_landmarks_proto = create_landmark_list(
        face_results.face_landmarks[0] if face_results.face_landmarks else None, 478 * 3
    )

    # convert pose landmarks to LandmarkList, using empty values if no landmarks are present
    pose_landmarks_proto = create_landmark_list(
        pose_results.pose_landmarks[0] if pose_results.pose_landmarks else None, 33 * 4
    )

    # convert hand landmarks to LandmarkList, using empty values if no landmarks are present
    hand_landmarks_proto = [
        create_landmark_list(hand_landmarks, 21 * 3)
        for hand_landmarks in (
            hand_results.hand_landmarks
            if hand_results.hand_landmarks
            else [None, None]  # two hands
        )
    ]

    return face_landmarks_proto, pose_landmarks_proto, hand_landmarks_proto

In [6]:
def extract_keypoints(face_results, pose_results, hand_results):
    """Extracts keypoints from face, pose, and hand results for dataset creation.

    Handles cases with zero, one, or two hands, assigning hand keypoints based
    on handedness information.

    Args:
      face_results: Object containing face landmark data (if available), assumed to
                    have a `face_landmarks` attribute with landmark data.
      pose_results: Object containing pose landmark data (if available), assumed to
                    have a `pose_landmarks` attribute with landmark data.
      hand_results: Object containing hand landmark data (if available), assumed to
                    have `hand_landmarks` and `handedness` attributes.

    Returns:
      A tuple containing three NumPy arrays representing flattened keypoints for face,
      pose, and hand, respectively. Empty arrays are used for missing modalities.
    """

    # extract face keypoints if available, otherwise return a zero-filled array
    face_keypoints = (
        np.array(
            [
                [landmark.x, landmark.y, landmark.z]
                for landmark in face_results.face_landmarks[0]
            ]
        ).flatten()
        if face_results.face_landmarks
        else np.zeros(478 * 3)  # 478 landmarks with 3 coordinates each (x, y, z)
    )

    # extract pose keypoints if available, otherwise return a zero-filled array
    pose_keypoints = (
        np.array(
            [
                [landmark.x, landmark.y, landmark.z, landmark.visibility]
                for landmark in pose_results.pose_landmarks[0]
            ]
        ).flatten()
        if pose_results.pose_landmarks
        else np.zeros(33 * 4)  # 33 landmarks with 4 values each (x, y, z, visibility)
    )

    # initialize hand keypoints with zeros for two hands (right and left),
    # each with 21 landmarks and 3 coordinates
    hand_keypoints = np.zeros((2, 21, 3))

    # if no hand results are available, return the empty hand keypoints
    # and concatenate it with face and pose keypoints
    if not hand_results:
        return np.concatenate(
            [face_keypoints, pose_keypoints, hand_keypoints.flatten()]
        )

    # iterate over the detected hand landmarks
    for idx in range(len(hand_results.hand_landmarks)):
        # determine the hand index (0 for right hand, 1 for left hand) using handedness information
        handedness = hand_results.handedness[idx][0].index

        # extract the keypoints for the current hand and assign them to the appropriate index
        hand_keypoints[handedness] = np.array(
            [[lm.x, lm.y, lm.z] for lm in hand_results.hand_landmarks[idx]]
        )

    # flatten the hand keypoints array and concatenate it with face and pose keypoints
    return np.concatenate([face_keypoints, pose_keypoints, hand_keypoints.flatten()])

In [7]:
def draw_detection_landmark(
    image,
    face_landmarks_proto=None,
    pose_landmarks_proto=None,
    hand_landmarks_proto=None,
):
    # draw landmark face
    drawer.draw_landmarks(
        image,
        face_landmarks_proto,
        mp.solutions.face_mesh.FACEMESH_CONTOURS,
        drawer.DrawingSpec(color=(80, 60, 20), thickness=1, circle_radius=1),
        drawer.DrawingSpec(color=(80, 146, 241), thickness=1, circle_radius=1),
    )

    # draw landmark pose
    drawer.draw_landmarks(
        image,
        pose_landmarks_proto,
        mp.solutions.pose.POSE_CONNECTIONS,
        drawer.DrawingSpec(color=(80, 22, 10), thickness=2, circle_radius=3),
        drawer.DrawingSpec(color=(80, 44, 121), thickness=2, circle_radius=2),
    )

    # draw landmark for both hand (right, left)
    for idx in range(len(hand_landmarks_proto)):
        drawer.draw_landmarks(
            image,
            hand_landmarks_proto[idx],
            mp.solutions.hands.HAND_CONNECTIONS,
            drawer.DrawingSpec(color=(121, 22, 76), thickness=2, circle_radius=2),
            drawer.DrawingSpec(color=(121, 44, 250), thickness=2, circle_radius=2),
        )

In [8]:
def calculate_fps(start_time, frames):
    elapsed_time = time.time() - start_time
    return frames / elapsed_time if elapsed_time > 0 else 0


def draw_fps(image, fps):
    cv2.putText(
        image,
        f"FPS: {round(fps, 2)}",
        (10, 40),
        cv2.FONT_HERSHEY_SIMPLEX,
        1.5,
        (0, 255, 0),
        2,
    )

In [9]:
colors = [(245, 117, 16), (117, 245, 16), (16, 117, 245),
          (117, 117, 16), (16, 245, 117), (245, 117, 245)]

def confidence_bar(res, actions, input_frame, colors):
    output_frame = input_frame.copy()

    for num, prob in enumerate(res):
        cv2.rectangle(
            output_frame,
            (0, 60 + num * 40),
            (int(prob * 100), 90 + num * 40),
            colors[num],
            -1,
        )

        cv2.putText(
            output_frame,
            actions[num],
            (0, 85 + num * 40),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )

    return output_frame

In [10]:
# sign action to be detected
ACTIONS = np.array(
    [
        "hello",
        "thanks",
        "i-love-you",
        "see-you-later",
        "I",
        "Father",
        "Mother",
        "Yes",
        "No",
        "Help",
        "Please",
        "Want",
        "What",
        "Again",
        "Eat",
        "Milk",
        "More",
        "Go To",
        "Bathroom",
        "Fine",
        "Like",
        "Learn",
        "Sign",
        "Done",
    ]
)

ACTIONS = ACTIONS[:6]

In [11]:
ACTIONS

array(['hello', 'thanks', 'i-love-you', 'see-you-later', 'I', 'Father'],
      dtype='<U13')

In [12]:
from tensorflow.keras.models import Sequential  # type: ignore
from tensorflow.keras.layers import BatchNormalization, Conv1D, MaxPooling1D, Flatten, Dense, Dropout, LSTM, TimeDistributed, Reshape, Bidirectional  # type: ignore
from tensorflow.keras.callbacks import TensorBoard, EarlyStopping, ReduceLROnPlateau  # type: ignore
from tensorflow.keras.regularizers import l2  # type: ignore
from tensorflow.keras.optimizers import Adam # type: ignore

In [13]:
# the input shape (30, 1692) where 30 is the sequence length and 1692 is the number of features per frame
input_shape = (30, 1692)

In [14]:
model = Sequential()

# data normalization
model.add(BatchNormalization(input_shape=input_shape))

# first Conv1D layer with L2 regularization
model.add(
    Conv1D(filters=64, kernel_size=3, activation="relu", kernel_regularizer=l2(0.01))
)  # changed kernel size and filters
model.add(MaxPooling1D(pool_size=2))

# second Conv1D layer with L2 regularization
model.add(
    Conv1D(filters=128, kernel_size=3, activation="relu", kernel_regularizer=l2(0.01))
)  # changed kernel size and filters
model.add(MaxPooling1D(pool_size=2))

# third Conv1D layer with L2 regularization
model.add(
    Conv1D(filters=256, kernel_size=3, activation="relu", kernel_regularizer=l2(0.01))
)  # changed kernel size and filters
model.add(MaxPooling1D(pool_size=2))

# dense layer for feature extraction with L2 regularization
model.add(Dense(64, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.5))

# bidirectional LSTM layer with L2 regularization
model.add(
    Bidirectional(
        LSTM(
            512, return_sequences=False, activation="relu", kernel_regularizer=l2(0.01)
        )
    )
)

# dense layers for classification with dropout for regularization
model.add(Dense(128, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.5))  # slightly higher dropout rate, so it's not overfitting
model.add(Dense(64, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.5))  # slightly higher dropout rate, so it's not overfitting

model.add(Dense(ACTIONS.shape[0], activation="softmax"))


# Load pre-trained weights

model.load_weights(
    "../models/legacy/asl-action-cnn-lstm_1l-6a-es_p30__rlr_f05_p10_lr1e6-2.9M.h5"
)

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 batch_normalization (Batch  (None, 30, 1692)          6768      
 Normalization)                                                  
                                                                 
 conv1d (Conv1D)             (None, 28, 64)            324928    
                                                                 
 max_pooling1d (MaxPooling1  (None, 14, 64)            0         
 D)                                                              
                                                                 
 conv1d_1 (Conv1D)           (None, 12, 128)           24704     
                                                                 
 max_pooling1d_1 (MaxPoolin  (None, 6, 128)            0         
 g1D)                                                            
                                                        

In [17]:
sequences = []
sequence = []

sentence = []
predictions = []

sequence_length = 30
threshold = 0.2

In [18]:
cap = cv2.VideoCapture(0)

# set capture properties
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 600)  # set width to 600 pixels
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 600)  # set height to 600 pixels
cap.set(cv2.CAP_PROP_FPS, 60)  # set frame rate to 60 FPS

start_time = time.time()
isQuit = False

while cap.isOpened():
    success, image = cap.read()

    if not success:
        print("Ignoring empty camera frame.")
        continue

    # NOTE: using flip image will screw'ed up some of the keypoints
    #       data for training the model later
    # image = cv2.flip(image, 1) # flip the image horizontally for a selfie-view display.

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # get current frame timestamp in milliseconds
    timestamp_ms = int(cap.get(cv2.CAP_PROP_POS_MSEC))

    # convert cv image to mediapipe image format before being
    # passed to face, pose and hand detector
    annotated_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image_rgb)

    face_results = face_detector.detect_for_video(
        image=annotated_image, timestamp_ms=timestamp_ms
    )

    hand_results = hand_detector.detect_for_video(
        image=annotated_image, timestamp_ms=timestamp_ms + 1
    )

    pose_results = pose_detector.detect_for_video(
        image=annotated_image, timestamp_ms=timestamp_ms + 2
    )

    keypoints = extract_keypoints(face_results, pose_results, hand_results)
    sequences.append(keypoints)
    sequence = sequences[-30:]

    face_proto, pose_proto, hand_proto = extract_keypoints_for_drawing(
        face_results, pose_results, hand_results
    )

    draw_detection_landmark(
        image_rgb,
        face_landmarks_proto=face_proto,
        pose_landmarks_proto=pose_proto,
        hand_landmarks_proto=hand_proto,
    )

    if len(sequence) == sequence_length:
        # predict the action label based on the sequence of keypoints
        result = model.predict(
            np.expand_dims(
                sequence, axis=0
            )  # expanded to include a batch dimension before fed to the model
        )[0]

        # action class with the highest confidence score
        predictions.append(np.argmax(result))

        # NOTE: If the current prediction matches the most common prediction over the last 10 frames,
        #       it suggests that the current action is likely intentional and
        #       consistent with recent actions, rather than a momentary anomaly.
        if np.unique(predictions[-10:])[0] == np.argmax(result):

            # check if the confidence score of the current prediction index is above the threshold.
            if result[np.argmax(result)] > threshold:

                # checks if there are any elements in the sentence list.
                # If it's not empty, it means there are already recognized actions in the sentence.
                if len(sentence) > 0:
                    # compares the current predicted action
                    if ACTIONS[np.argmax(result)] != sentence[-1]:
                        sentence.append(ACTIONS[np.argmax(result)])
                else:
                    # no recognized actions yet
                    sentence.append(ACTIONS[np.argmax(result)])

        # limit the length of the recognized action sentence to 5 elements by
        # keeping only the last two elements so it does not exceed the text box
        if len(sentence) > 3:
            sentence = sentence[-3:]

        # overlay the predicted action on the image
        image_rgb = confidence_bar(result, ACTIONS, image_rgb, colors)

    cv2.rectangle(image_rgb, (0, 0), (640, 40), (245, 117, 16), -1)
    cv2.putText(
        image_rgb,
        " ".join(sentence),
        (3, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        1,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )

    cv2.imshow(
        "MediaPipe Detection",
        cv2.cvtColor(image_rgb, cv2.COLOR_BGR2RGB),
    )

    if cv2.waitKey(10) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 22ms/step


In [28]:
len(sequences[-1])

1692

In [25]:
sequences[-30:]

[array([ 0.44544238,  0.64115947, -0.03221599, ...,  0.68736714,
         0.15755503, -0.03414574]),
 array([ 0.4241001 ,  0.64154488, -0.03354746, ...,  0.68954688,
         0.18421464, -0.04341972]),
 array([ 0.41484895,  0.6365031 , -0.03500032, ...,  0.70758289,
         0.20392089, -0.05015678]),
 array([ 0.41598654,  0.63779616, -0.03486504, ...,  0.71803403,
         0.20868723, -0.04683249]),
 array([ 0.42308158,  0.63875502, -0.03319922, ...,  0.71029013,
         0.22282177, -0.04957622]),
 array([ 0.42920461,  0.63961667, -0.03309668, ...,  0.70143288,
         0.22622743, -0.0486876 ]),
 array([ 0.43300113,  0.63974082, -0.03372842, ...,  0.68814057,
         0.22561495, -0.05403432]),
 array([ 0.43304485,  0.63810652, -0.0344034 , ...,  0.69318217,
         0.22982906, -0.05250174]),
 array([ 0.43698582,  0.63826382, -0.03390885, ...,  0.69646907,
         0.22186863, -0.05552857]),
 array([ 0.43681186,  0.63832694, -0.033496  , ...,  0.68825656,
         0.21784976, -0.06

In [27]:
np.expand_dims(sequence, axis=0)

array([[[ 0.44544238,  0.64115947, -0.03221599, ...,  0.68736714,
          0.15755503, -0.03414574],
        [ 0.4241001 ,  0.64154488, -0.03354746, ...,  0.68954688,
          0.18421464, -0.04341972],
        [ 0.41484895,  0.6365031 , -0.03500032, ...,  0.70758289,
          0.20392089, -0.05015678],
        ...,
        [ 0.45594773,  0.6600616 , -0.03476332, ...,  0.67552382,
          0.2079975 , -0.06252488],
        [ 0.45720953,  0.6630789 , -0.03467686, ...,  0.67477727,
          0.20574172, -0.05966702],
        [ 0.45570692,  0.67044806, -0.03467299, ...,  0.67064601,
          0.20621949, -0.06282526]]])

In [26]:
pred = model.predict(np.expand_dims(sequence, axis=0))[0]

print(ACTIONS[np.argmax(pred)])

1/1 [==============================] - 0s 50ms/step
hello
